name: phpunit tests
on: [push, pull_request]

jobs:
  php81-tests:
    name: php 8.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          php_version: 8.1

  php82-tests:
    name: php 8.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          php_version: 8.1
